### ISSUE TITLE
Feature Request: Node.js

### ISSUE THREAD

**Issue by RaphiePS** [joostn/OpenJsCad#12]
It'd be incredibly useful if this could be refactored into a node module. Then one could render on the server.

**Comment by matiasinsaurralde** [comment]
A bower module could be useful too!

**Comment by z3dev** [comment]
@RaphiePS @matiasinsaurralde This is done. Please see https://github.com/jscad/csg.js as part of the new organization for OpenJSCAD libraries.

I will close this issue in 30 days.
