### ISSUE TITLE
rendering options

### ISSUE THREAD

**Issue by joshmarinacci** [joostn/OpenJsCad#33]
It would be nice if I could customize the view. I've hacked in setters for the viewer width and height, but there's a bunch of other things that would be useful to modify:

change size of the viewer
turn on lines
turn off sides
change default model color
change default mouse controls
switch to orthographic projection
disable the default status line and dropboxes.

**Comment by z3dev** [comment]
@joshmarinacci All of these are possible via OpenJSCAD.org viewer.
