### ISSUE TITLE
Feature request: render 2d paths

### ISSUE THREAD

**Issue by matthijskooijman** [joostn/OpenJsCad#45]
Currently, the rendering result can only be CAG/CSG objects. However, I want to mark some lines using a laser cutter, for which 2d paths seem a perfect match. However, it's not currently possible to return these paths, even though it should be possible to represent them in a DXF file.

**Comment by rogerclarkmelbourne** [comment]
Can someone tell me the current status of the 2D path support ?

There is some example code that seems to indicate that you can have open 2D paths, e.g.
But the default viewer at http://openjscad.org/ won't render this code

```
function main() {
   
   var path = new CSG.Path2D([ [10,10], [-10,10] ], /* closed = */ false);
var anotherpath = new CSG.Path2D([ [-10,-10] ]);
path = path.concat(anotherpath);
path = path.appendPoint([10,-10]);
path = path.close(); // close the path

// of course we could simply have done:
// var path = new CSG.Path2D([ [10,10], [-10,10], [-10,-10], [10,-10] ], /* closed = */ true);

// We can make arcs and circles:
var curvedpath = CSG.Path2D.arc({
  center: [0,0,0],
  radius: 10,
  startangle: 0,
  endangle: 180,
  resolution: 16,
});
   
   
   
   return curvedpath;
}
```

As I get this error

> Error: Your main() function does not return valid data. It should return one of the following: a CSG object, a CAG object, an array of CSG/CAG objects, or an array of objects: [{name:, caption:, data:}, ...] where data contains a CSG or CAG object.

**Comment by joostn** [comment]
Hi Roger,

The viewer cannot render Path2D objects. You need to convert your path to a CAG. Either use:

return path.expandToCAG(pathradius, resolution);
This will trace the path with a circle of the given thickness (set resolution = 16 for a start)

or return path.innerToCAG();
This will create a filled 2D polygon. Obviously this only works for closed paths.

**Comment by rogerclarkmelbourne** [comment]
@joostn 
Thanks.

I've tried using expandToCAG but like you say it results in a closed path, and I hoped to be able to export 2D paths.

The reason I want 2D paths that are open is for laser cutting, and sometimes i just need to cut individual paths and not closed objects

**Comment by danmarshall** [comment]
Hi @rogerclarkmelbourne - take a look at my library [Maker.js](https://github.com/Microsoft/maker.js) which might be more appropriate for laser cutting and open 2D paths. Plus, Maker.js has an "exit strategy" to get you back into OpenJsCad, it can generate the OpenJsCad code from a 2D path (if the path is closed).

**Comment by rogerclarkmelbourne** [comment]
@danmarshall 

Thanks Maker.js seems to fit the bill, especially as it can generate OpenJsCad code (as long as the paths are closed)

I think I'll need to use a combination of OpenJsCad and Maker.js.
Depending on what I'm trying to create,  quite often its good to visualize how all the 2D parts would be assembled e.g. when designing something like a box, which has interlocking sides.

i.e Export 2D from Maker.js (omitting the open paths), into OpenJsCad for 3D visualisation

Thanks again

Roger

**Comment by z3dev** [comment]
The V2 viewer will render paths as well. Coming soon.

Can I close this issue? It has way too many topics rolled into one big discussion without a resolution. At this point, this discussion is worthless. If something needs to persist then open a new issue.

**Comment by rogerclarkmelbourne** [comment]
I'm happy for you to close it.  But I didn't start the thread

**Comment by matthijskooijman** [comment]
I'm not really actively using OpenJsCad right now, so I'm not sure how much of this issue has been resolved already. I'm fine with closing it for now, when I start another project with OpenJsCad and find things are still missing, I'll open a new issue.
