### ISSUE TITLE
Feature request: SVG export

### ISSUE THREAD

**Issue by matthijskooijman** [joostn/OpenJsCad#46]
Having a direct SVG export feature would be helpful - it allows using the generated file directly in e.g. jscut. OpenSCAD also recently gained an SVG export, perhaps that might be useful to  look at?

**Comment by z3dev** [comment]
SVG import and export were released as part of OpenJSCAD.org 0.5.0.

**Comment by VVZen** [comment]
Is it still experimental?
I don't see it in the main page of OpenJSCAD.org .

**Comment by z3dev** [comment]
@matthijskooijman Please review the funcationality provided as part of OpenJSCAD.org. If that is sufficient then please close this issue.

I will close this issue in 30 days if no reply is received.

**Comment by matthijskooijman** [comment]
@z3dev, I"m a bit confused. It seems that the joostn version, which this issue is about, does not support SVG export yet, so why would this issue be closed? Unless you have decided to only work on the internals and leave the UI to openjscad.org, in which case you should close this issue as wontfix, not me.

As for the SVG export of openjscad.org, I've done a very quick test (though most of my code is in openjscad format, not openjscad.org format) and [reported an issue I noticed with the export](https://github.com/Spiritdude/OpenJSCAD.org/issues/229).

**Comment by z3dev** [comment]
@matthijskooijman Thanks for the comments. I'll leave this open for now.

The CSG library has been moved to the new organization, and I believe that the CSG library will be integrated into openjscad from the new home.

**Comment by z3dev** [comment]
Closing. As this will not be fixed in this version of OpenJsCad
