### ISSUE TITLE
Feature request: Text rendering

### ISSUE THREAD

**Issue by matthijskooijman** [joostn/OpenJsCad#47]
It would be useful to support rendering of text into a CAG. Openjscad.org [has some code for this](https://github.com/Spiritdude/OpenJSCAD.org/blob/123ce5e2413477a2878f7bff490cf8a3e1d658df/openscad.js#L1250-L1868) that could be used. That does use a hardcoded "font", for more flexibility [opentype.js](https://github.com/nodebox/opentype.js/blob/master/README.md) seems promising (it allows uploading a ttf or otf file and then renders a text to a path).

**Comment by z3dev** [comment]
@matthijskooijman There's a new pull request which has implemented a new 'text()' function, based on opentype.js. This will become part of the CSG.js library in the very near future.

https://github.com/jscad/csg.js/pull/106

How about trying this out and giving a little feedback to the author?

**Comment by z3dev** [comment]
Here's a small module that shows how to use TTF fonts with JSCAD V2. I think this can be closed now.

https://github.com/jscad-community/jscad-text
