### ISSUE TITLE
Feature request: SVG import

### ISSUE THREAD

**Issue by risacher** [joostn/OpenJsCad#57]
It would be useful to be able to design a path in an SVG tool (like Inkscape) and pull that into OpenJsCad as a CAG or something similar.

**Comment by bebbi** [comment]
yes that would be nice.
maybe have a quick look at
https://github.com/Spiritdude/OpenJSCAD.org/issues/74,
this is roughly related - once formats are separated out, maybe it's an opportunity to add something in there?

**Comment by z3dev** [comment]
SVG import and export were released as part of OpenJSCAD.org 0.5.0.

**Comment by z3dev** [comment]
Closing as this has been addressed as part of OpenJSCAD.org, which is now part of jscad organization.
