### ISSUE TITLE
Signiture of setColor() is inconsist

### ISSUE THREAD

**Issue by z3dev** [joostn/OpenJsCad#65]
The newest version of CSG.js has introduced inconsistency in CSG.prototype.setColor(r,g,b,a) and CSG.Polygon.prototype.setColor([r,g,b,a])

As for the correct signature, I suggest supporting setColor([r,g,b,a]) as the provides the best performance, i.e. the array can be stored directly.

We (CSG.js users) can easily convert from r,g,b,a to [r,g,b,a] as well.

**Comment by bebbi** [comment]
Tx, I'll look into this. not sure I get the performance argument. Do you plan to submit additional bugs so I can look at it when we have them together?

**Comment by Spiritdude** [comment]
I recommend to permit both: setColor(r,g,b(,a)) and setColor([r,g,b(,a)])

**Comment by z3dev** [comment]
Please address this issue first.

The CSG.Shared object retains an array. So, passing the color specification by array will improve performance. Although, permitting both styles would probably be the best for the users of CSG.js.

**Comment by bebbi** [comment]
@z3dev that's an easy one, can you write a pull request against gh-pages? I'd tend to support the version that's already documented but I'm fine with supporting both for both setColor functions. If I understood you well, I don't believe there's a performance difference in creating an array inside a function call vs inside a function body.

**Comment by z3dev** [comment]
Hello. I don't have a patch for this.

Please correct and let me know when the new version is available.

**Comment by joostn** [comment]
See https://github.com/joostn/OpenJsCad/pull/66
I'm proposing to use the array syntax from now on, with the previous syntax supported for backwards compatibility, I don't think performance is relevant here.
