### ISSUE TITLE
Feature Request: RoundRadius on CSG.roundedCylinder()

### ISSUE THREAD

**Issue by z3dev** [joostn/OpenJsCad#72]
This is a very useful function to make rounded cylinders of a given radius, but the rounded end of the cylinder should also be configurable. Currently, the rounded end of the cylinder is the same as the radius of the cylinder. But anything between 0 < rounded end radius <= radius is possible.

Parameters:
    //   start: start point of cylinder (default [0, -1, 0])
    //   end: end point of cylinder (default [0, 1, 0])
    //   radius: radius of cylinder (default 1), must be a scalar
    //   resolution: determines the number of polygons per 360 degree revolution (default 12)
    //   normal: a vector determining the starting angle for tesselation. Should be non-parallel to start.minus(end)

Add...
// roundedRadius: radius of rounded end of cylinder, default radius of cylinder

![1](https://cloud.githubusercontent.com/assets/8969165/10211283/765a06c6-682c-11e5-9d1b-5a03c1407da1.png)

**Comment by bebbi** [comment]
That would be a reasonable addition. I don't have the time now, but do you want to take a stab at it? I would probably go about it by replacing the existing logic with something like this:
1. create a path, using arc, with all params (radius, roundradius, height)
2. convert to CAG using path.innerToCAG()
3. rotateExtrude to CSG
This way, if you want you could even expose the angle param of rotateExtrude as a sectorAngle argument for rounded cylinder pies.

**Comment by z3dev** [comment]
@bebbi thanks
My version was very similar, but I used solidFromSlices(). It's just a matter of following the points, and scaling the circle.

FYI, there seem to be issues with using rotateExtrude with a CAG that has a zero(0) X offset. The internal vertices seemed to be confused.

**Comment by bebbi** [comment]
From http://joostn.github.io/OpenJsCad/ docu:
// Note: for this to work, shape shouldn't have point in negative x space
If the CAG is valid and all x>=0 overall, it should work - if not, maybe you can open an issue with the example?

Again, please feel free to post PRs to csg.js I’m tight on time right now, so any help is appreciated.

**Comment by z3dev** [comment]
This issue was moved to jscad/csg.js#21
