### ISSUE TITLE
Offline - works only in Chrome not IE

### ISSUE THREAD

**Issue by TommyK82** [joostn/OpenJsCad#88]
Hi,

I have downloaded this customizer (http://joostn.github.io/OpenJsCad/)  via "Git GUI" and it works only in Chrome ... in Internet Explorer (IE)  it doesn't work   ... no part is shown and below the picture is written "Aborted".

The weird thing is that the website itself (http://joostn.github.io/OpenJsCad/)  is running at the internet explorer.  

What have I done wrong?

Many thanks

Edit:  the error message is:   SecurityError
(file ..../src/openjscad.js line 512)

**Comment by joostn** [comment]
It's a security restriction in Internet Explorer: IE will not run web workers from a Blob if the html page is on the local computer. I'm not aware of any work around.
