### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [joostn/OpenJsCad#91]
Does OpenJsCad require anything but a webserver to run or does it rely on something? (eg node, frameworks, etc.)
And I also wish to know, which of these features are supported?
drawing units
draw lines/ellipses/elliptical arc/rectangles/polygon/polyline/spline/donuts/points
erasing objects
layers
translate/rotate/scale objects
adding text
filling with hatches/patterns/gradients/textures
referencing objects
printing and plotting
importing and exporting geometry

Thanks in advance for any help.

Bye, Ivano.

**Comment by z3dev** [comment]
@berserk82 Welcome!

However, OpenJsCad is now part of the JSCAD organization, which maintains the libraries and the various pieces of the web pages. https://github.com/jscad

You can find more information about the project here.
